### ISSUE TITLE
Question about licence of this project.

### ISSUE THREAD

**Issue by irino** [zebra-rs/zebra-rs#54]
I want to know about licence of this repository.
LICENSE (https://github.com/zebra-rs/zebra-rs/blob/main/LICENSE) file shows Apache License.
On the other hand zebra's mainr.rs (https://github.com/zebra-rs/zebra-rs/blob/main/zebra/src/main.rs) shows GPL-3.0-or-later.
Which license will be used in this project?

**Comment by kishiguro** [comment]
We are planning to use GPLv3.

**Comment by irino** [comment]
Thanks for reply.
